### ISSUE TITLE
~S2ram~ Reboot broken, maybe a solution

### ISSUE THREAD

**Issue by theotherjimmy** [samueldr/wip-pinebook-pro#1]
Hi @samueldr,

I'm also looking into running NixOS on my PBP-ANSI, and I'd like to help fix the S2Ram issue. 
It looks like TF-A master contains a fix that claims to fix hangs when resuming from a soft-reset, which may be related to the post-suspend hang. link to the commit: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?id=b4899041e5f0b8e8b388c6511b5233516b8785ec

Master of TF-A builds with this repo as of last night, but I have not tested the resulting SD image.

Further, I noticed that the TF-A community does not know about this issue, so if that fix is not the final fix, we should capture as much relevant debug information and open an issue with them.

**Comment by samueldr** [comment]
Oh, interesting!

To be fair, I did zero investigation, only saw a report of someone using `s2idle` temporarily until this is fixed, and saw the immediate benefit.

With the wording, if this doesn't help with suspend, it may just as well help with rebooting.

Thanks for the mention, I'll update to master TF-A locally, test, and report back.

**Comment by samueldr** [comment]
Looks like my intuition is right. This doesn't help with suspend, but does seem to fix reboot. I've been rebooting a couple of times with the latest `master` commit of ATF built with u-boot and it always reboots fine. While not the issue you'd hope, still one issue knocked! Thank you for spotting this!

(Chatter I heard through the grapevine seem to indicate the suspend fix would happen kernel-side.)

I'll close since the crux of this issue has been investigated and implemented, even though it doesn't fix the suspend issue. If or whenever you spot anything relevant to suspend please feel free to open a new issue!

**Comment by theotherjimmy** [comment]
Alright! I'll have to investigate the cause of the suspend failure in more detail. I'll open another issue here if I find anything concrete.
