### ISSUE TITLE
Fails to boot when installed

### ISSUE THREAD

**Issue by deingithub** [samueldr/wip-pinebook-pro#19]
Hey, first of all a massive thanks for building this in the first place to all contributors. Don't know if this is the appropriate channel for this but I'll try anyway:  
I want to use NixOS on my freshly acquired PBP, so I started out by creating a SPI flash image following the instructions from the feature/gfx-u-boot https://github.com/samueldr/wip-pinebook-pro/commit/ee3d667e841bc4c1fc8338b340148b12fa9397d1 's `FIRMWARE.md`. That worked out very nicely, I get an initial screen now with a proper boot menu.

Then I set out to actually install nixos on it. So I booted into an USB image and started [the regular install process](https://nixos.org/manual/nixos/stable/index.html#sec-installation). I mounted and partitioned the eMMC — based off the understanding that no special aligning for U-Boot or other similarly arcane stuff is needed anymore thanks to the modified version in the SPI. I also set `boot.kernelPackages = pkgs.linuxPackages_pinebookpro_lts;`, giving me a 5.4.x kernel.  
With a fairly minimal configuration (no graphics, for example) I ran `nixos-install`, which took its time (almost exactly three hours as it needed to compile the kernel). Until then everything seemed pretty much perfect.  
However, on reboot I'm faced with a problem: I can either boot from USB and get the screen to turn on, with no apparent pattern to it, about 1/5th of a time — tedious, but doable — or boot from the eMMC (which displays a correct NixOS generation-select menu) and have the kernel softlock after a few messages of fairly inconspicuous output:
```
[ 2.110697] vcc_sdio: unsupportable voltage range: 3300000-3000000uV
[ 2.745239] rockchip-pcie f8000000.pcie: PCIe link training gen1 timeout!
[ 3.066000] rockchip-dp ff970000.edp: no DP phy configured
[ 3.082182] OF: graph: no port node found in /i2c@ff3d0000/fusb30x@22
[ 3.089189] usb 2-1.2: device not accepting address 3, error -71
[68.581337] cdn-dp fec0000.dp: [drm:cdn_dp_pd_event_work [rockchipdrm]] *ERROR* Timed out trying to load firmware
```
After this, I only get to see a blinking cursor. The kernel still responds to Ctrl-Alt-Delete by rebooting.

Has anyone experienced a similar problem, and even better, has found a solution to it? Am I going at this the wrong way in some form (i.e. using `nixos-install`, using the eMMC,…)?

**Comment by samueldr** [comment]
Depending on the exact firmware installed to SPI flash (the first line should show a version, from I think 001 to 004), different patches have been applied to u-boot.

With 004, it has not been verified whether 5.4 with patches boots correctly.

AFAIK cdn-dp is for the Type-C adapter's graphics output. It shouldn't matter for the internal display. If these messages bothered you.

The USB image, what was it built from? A commit from #13? And it's the SD image, right? I'm not sure a UEFI iso has been verified as working. Though I guess since you booted successfully from it, it's less of an issue. You can check which kernel it's using, it might give some clues.

And your installed system, is it built using a commit from #13? You're including the recommended settings from the repo with something similar to `imports = [ ./wip-pinebook-pro/pinebook_pro.nix ];`? I don't know if it would be a problem or not to not use those settings.

**Comment by glglwty** [comment]
I'm stuck with the same kernel message but I'm on master branch and used the master branch u-boot (flashed to EMMC; my SPI should be empty) + kernel 5.7. I wanted to set up LUKS so I flashed an sdcard with the img built from master branch and with it working tried to install nixos to another SD card. I created ext4 /boot partition and encrypted root, nothing special. It boots with the same kernel message OP posted and was stuck there. Yes I did include `imports = [ ./wip-pinebook-pro/pinebook_pro.nix ]`; 

I tried random tweaks and none of them works:
- Using kernel 5.8 from the feature branch (didn't flash the u-boot).
- Tried GPT and MBR (they all booted to stage 1 so don't seem to matter).
- I tried removing all the kernel modules after "pwm_bl" and it didn't make a difference ([this post](https://forum.pine64.org/showthread.php?tid=9052) has a different set of initrd kernel modules. I tried copying it and the screen doesn't light up.)
- Tried to install to EMMC instead of sdcard and it's the same thing.

Some observations:
- I looked at the dmesg on the working SD card, it doesn't seem to have this "*ERROR* Timed out trying to load firmware" line. Looks like it comes from here https://dri-devel.freedesktop.narkive.com/equIaM8x/patch-v17-0-7-drm-rockchip-add-cdn-dp-driver
- On the working system disks are initialized after these "OF: graph: no port node found in /i2c@ff3d0000/fusb30x@22" lines (I think initializing /dev is one of the last steps of stage 1).
- I compared the /boot partition between the flashed image and my attempted installation and they looked pretty similar, with the same dtb files. 

I don't have a serial adapter so I don't know what happened before the screen is on.

**Comment by deingithub** [comment]
Okay, update: I got it to boot by adding two of the [kernel options the SD image uses](https://github.com/samueldr/wip-pinebook-pro/blob/master/nixos/sd-image-aarch64.nix#L19-L29), specifically `"cma=32M" "console=tty0"`. I'm on a SPI-flashed U-Boot version 003 built from https://github.com/samueldr/wip-pinebook-pro/commit/ee3d667e841bc4c1fc8338b340148b12fa9397d1, and my installation USB image was built from master at https://github.com/samueldr/wip-pinebook-pro/commit/7d2638c192955e7b21e0574018cfb4458ef68153 if I remember correctly. My configuration imports `./wip-pinebook-pro/pinebook_pro.nix` from the same commit as the SPI image.

**Comment by apatard** [comment]
Since https://github.com/samueldr/wip-pinebook-pro/pull/13 has been mentionned here, allow me to give some comments:

- the cdn-dp is for the usb-c display, and the error happens when the firmware for it (rockchip/dptx.bin) is not available. It should not be bloquing the boot
- I've not checked the schematics but the fusb is possibly used to use usbc a power supply (don't take my work on it, double check the schematics). Anyway, I've the same message in my boot logs on 5.9-rc4 (vanilla, with only this patch: http://people.hupstream.com/~rtp/pbp/20200911/linux-kernel-pwm-fixes.patch) and it's booting fine.

So theses two messages are not related to the issue

**Comment by apatard** [comment]
cma=32M ? i think it would be better to use 64M for CMA

**Comment by samueldr** [comment]
`cma=32M` comes from the defaults of the aarch64 installer image, from before I was involved with the project.

Do you think that, across the board, it should be increased to 64M for all aarch64 boards?

Even better, upstream documentation about cma= for distribution integrators?

**Comment by apatard** [comment]
From what I understand, the CMA size is dependant of the application / use of the board. And of the board too (I'm not convinced that using 64M buffer on a device with 256M is a good idea...)

In a bunch of cases, CMA buffers  is used to store framebuffer data, so a buffer needs to be big enough for 1080p. I don't know if 32M is enough for the PBP use case, but I'm pretty sure it fits in 64M.
fwiw, some bugs about CMA in distro BTS:

- https://bugzilla.redhat.com/show_bug.cgi?id=1127000
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911211

**Comment by pindarania** [comment]
My pinebook pro is stuck on black screen just a cursor on left side and power light blinking red and green , anybody know the solution ?? Tomorrow my paper and m going on shop they said its near about 3-4 days to fix it . Is this really a serious matter ?? Please 🥺 solution if u know , m a student and have no money to buy another laptop .. please uf anybody know then help me uits just your 4-5 minutes maximum but for me its my future . This exam is decide my future. 
              I will never forget your kindness, I don't have it today but in a few days I have nothing today to  send you a gift and you will remember that you helped someone

**Comment by emilylange** [comment]
To me, it looks like `cma=` is unrelated to this issue outlined here, assuming I did not misread it.

I encountered the same problem as OP but managed to boot successfully on the latest commit (caa3d3e324c369454da05ef6558c44ee1a0ee234) (LTS kernel) after adding `console=tty0` to the kernel parameters.
No need for `cma=`, at least as far as I can tell.

Notes:
- Tow-Boot 002
- Installing from sdcard to eMMC

Should I file a PR to add `console=tty0` to the kernel parameters in the following section? :)

https://github.com/samueldr/wip-pinebook-pro/blob/caa3d3e324c369454da05ef6558c44ee1a0ee234/pinebook_pro.nix#L44-L47

**Comment by samueldr** [comment]
It seems this issue became a magnet for unrelated issues. I'll try to answer some concerns.

Please open a new issue with a description of the symptoms and problem you're facing if it "fails to boot when installed", instead of commenting.

* * *

### `tty0`

Note that it might be needed to add `console=tty0` depending on your exact setup; the kernel will use `/chosen/stdout-path` by default. But I'm not adding this as a default as this is not something that's trivial to work around.

Here's how to check:

```
@luann ~ $ cat /proc/device-tree/chosen/stdout-path 
serial2:115200n8
```

In reality, the correct non-opinionated fix is to have the platform firmware (e.g. Tow-Boot) allow configuring the `/chosen/stdout-path`, something like *default operating system stdout*.

For now, this is something the end-user will have to know they have to configure :/.

This would be solved by having [console multiplexing](https://github.com/NixOS/nixpkgs/pull/123039) fixed in NixOS.

### CMA

End-users may want to configure `cma=___` values themselves, but *it should not be set as default anywhere*. Note that [as was found out](https://github.com/NixOS/nixpkgs/commit/c673c5ea981d16239f0685275ff0e5bfa40f7792) CMA must never be set by the distro using the kernel command-line parameter. I am considering a default config as "distro".

Also note that it now defaults to 32MiB at the kernel config level. So this is now always at least set this way.

When a platform requires more CMA, or a special configuration thereof (like the Raspberry Pi 4 family does), it should be configured in the device tree. And this is why setting `cma=___` in the cmdline is problematic: it overrides values from the device tree!

Also note that when investigating that initial issue, we found out that overprovisioning CMA is probably not an issue, as the kernel will dip in the CMA if it needs to for normal allocations.
