### ISSUE TITLE
Update keyboard/touchpad firmware updater to new fork, with new touchpad firmware

### ISSUE THREAD

**Issue by colemickens** [samueldr/wip-pinebook-pro#30]
We should have a firmware updater for the touchpad like for the keyboard:

From https://forum.pine64.org/showthread.php?tid=14531

>I'm feeling happy, excited, and a bit privileged Cool to announce the availability of the new vendor-provided touchpad firmware that fixes the issues we've all been experiencing with the Pinebook Pro touchpad.  One of the biggest issues was the initial lag upon finger movement, about which you can read more in this forum thread; it has been confirmed multiple times to be a touchpad issue and not a Linux issue.

>Based on the testing already performed by a few community members, myself included, this firmware update makes the touchpad very responsive and there are no traces of the dreaded initial delay.  I've also performed tests using the evtest utility, to eliminate any subjectivity, and the measured latency stays around or below 10 ms...  The numbers don't lie. Smile  You can read more about the evtest results with the old firmware in the above-linked forum thread.

>I've prepared an updated version of the keyboard and touchpad firmware update utility, which is available on GitHub.  Beside the updated touchpad firmware, my fork of the firmware updater brings other improvements, including improved feedback/status messages, improved handling of command-line arguments, added ability to cancel each update step, and improved documentation.

**Comment by samueldr** [comment]
> We should have a firmware updater for the touchpad like for the keyboard

We don't need to, it is the same updater! What we need to do is:

 - verify what firmware it uses for the keyboard
 - switch to that fork
 - ???
 - test correctly
 - ???
 - profit

We probably want to verify that detail about how to identify the controller, whether it is the "lite" variant or not. It was reported that it may be **extremely problematic** and while I don't think we should add anything to the updater, we should at least document how to verify the controller, and link to the different forum topics about how *problematic it may be*.

It is problematic as it was reported, for a specific user, that it would fail to flash the firmware as the 8 flashes were spent! So that user had no valid firmware on their keyboard.
